# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               groksrc.com
tagline:             'A blog for software engineers'
description:         'groksrc.com is a blog for sofware engineers. All thoughts are my own and do not represent those of my employer. Made by <a href="https://twitter.com/groksrc" target="_blank">@groksrc</a>.'
url:                 http://www.groksrc.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Drew Cain
  url:               https://twitter.com/groksrc
  email:             groksrc@gmail.com

# Custom vars
version:             1.0.0
